/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        navy: {
          DEFAULT: "#001d3d",
          50: "#e6eef5",
          100: "#b3cde0",
          200: "#80abcb",
          300: "#4d8ab6",
          400: "#1a68a1",
          500: "#005a9e",
          600: "#004d87",
          700: "#003f70",
          800: "#001d3d",
          900: "#001529",
        },
        crimson: {
          DEFAULT: "#e63946",
          50: "#fde8e9",
          100: "#f9b7bb",
          200: "#f5868d",
          300: "#f1555f",
          400: "#ed2430",
          500: "#e63946",
          600: "#d42230",
          700: "#a81b26",
          800: "#7c141c",
          900: "#500d12",
        },
        teal: {
          DEFAULT: "#0fa3b1",
          50: "#e6f7f8",
          100: "#b3e6ea",
          200: "#80d5dc",
          300: "#4dc4ce",
          400: "#1ab3c0",
          500: "#0fa3b1",
          600: "#0d8a96",
          700: "#0a717a",
          800: "#08585f",
          900: "#053f44",
        },
        golden: {
          DEFAULT: "#ff9f1c",
          50: "#fff5e6",
          100: "#ffe3b3",
          200: "#ffd180",
          300: "#ffbf4d",
          400: "#ffad1a",
          500: "#ff9f1c",
          600: "#e68a00",
          700: "#b36b00",
          800: "#804d00",
          900: "#4d2e00",
        },
        mint: {
          DEFAULT: "#70e000",
          50: "#f0fce6",
          100: "#d4f7b3",
          200: "#b8f280",
          300: "#9ced4d",
          400: "#80e81a",
          500: "#70e000",
          600: "#5db800",
          700: "#4a9000",
          800: "#366800",
          900: "#234000",
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        glass: "0 8px 32px 0 rgba(0, 0, 0, 0.5)",
        glow: "0 0 40px rgba(230, 57, 70, 0.3)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(230, 57, 70, 0.4)" },
          "50%": { boxShadow: "0 0 60px rgba(230, 57, 70, 0.8)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "slide-up": {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "float": "float 6s ease-in-out infinite",
        "slide-up": "slide-up 0.8s ease-out",
        "fade-in": "fade-in 0.6s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
